# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

CREATE TABLE "USER" ("MAIN_ID" SERIAL PRIMARY KEY, "ID" VARCHAR(100) NOT NULL);

CREATE TABLE "OAUTH1" ("ID" SERIAL PRIMARY KEY, "TOKEN" VARCHAR(200) NOT NULL, "SECRET" VARCHAR(200) NOT NULL);

CREATE TABLE "OAUTH2" ("ID" SERIAL PRIMARY KEY, "ACCESS_TOKEN" VARCHAR(200) NOT NULL, "TOKEN_TYPE" VARCHAR(200), 
	"EXPIRES_IN" INTEGER, "REFRESH_TOKEN" VARCHAR(200));

CREATE TABLE "PASSWORD" ("ID" SERIAL PRIMARY KEY, "HASHER" VARCHAR(100) NOT NULL, "PASSWORD" VARCHAR(100) NOT NULL, 
	"SALT" VARCHAR(100));

CREATE TABLE "MAIL_TOKEN" ("UUID" VARCHAR(100) PRIMARY KEY, "EMAIL" VARCHAR(300) NOT NULL, 
	"CREATION_TIME" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "EXPIRATION_TIME" TIMESTAMP NOT NULL, 
	"IS_SIGN_UP" BOOLEAN NOT NULL);

CREATE TABLE "PROFILE" ("ID" SERIAL PRIMARY KEY, "PROVIDER_ID" VARCHAR(50) NOT NULL, "USER_ID" VARCHAR(100) NOT NULL, 
	"FIRST_NAME" VARCHAR(100), "LAST_NAME" VARCHAR(100), "FULL_NAME" VARCHAR(200), 
	"EMAIL" VARCHAR(300), "AVATAR_URL" VARCHAR(500), "AUTH_METHOD" VARCHAR(50) NOT NULL,
	"OAUTH1_ID" INTEGER REFERENCES "OAUTH1" ("ID"), "OAUTH2_ID" INTEGER REFERENCES "OAUTH2" ("ID"), 
	"PASSWORD_ID" INTEGER REFERENCES "PASSWORD" ("ID"));

CREATE TABLE "AUTHENTICATOR" ("ID" VARCHAR(2000) PRIMARY KEY, "USER_ID" VARCHAR(100) NOT NULL, 
	"EXPIRATION_DATE" TIMESTAMP NOT NULL, 
	"LAST_USED" TIMESTAMP NOT NULL, "CREATION_DATE" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL);

CREATE TABLE "SERIES" ("ID" SERIAL PRIMARY KEY, "NAME" VARCHAR(50) NOT NULL, "DESCRIPTION" VARCHAR(100), 
	"CREATION_DATE" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL);

CREATE TABLE "STORY" ("ID" SERIAL PRIMARY KEY, "TITLE" VARCHAR(50) NOT NULL, "SUMMARY" VARCHAR(1000), 
	"SERIES_ID" INTEGER NOT NULL REFERENCES "SERIES" ("ID"), "CREATION_DATE" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL);

CREATE TABLE "PAGE" ("SEQUENCE" INTEGER DEFAULT 0 NOT NULL, "STORY_ID" INTEGER NOT NULL REFERENCES "STORY" ("ID"), 
	"IMAGE_PATH" VARCHAR(100) NOT NULL, "IS_COVER" BOOLEAN DEFAULT TRUE NOT NULL, 
	"CREATION_DATE" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY("SEQUENCE", "STORY_ID"));

# --- !Downs

DROP TABLE "PAGE";
DROP TABLE "STORY";
DROP TABLE "SERIES";
DROP TABLE "AUTHENTICATOR";
DROP TABLE "PROFILE";
DROP TABLE "MAIL_TOKEN";
DROP TABLE "PASSWORD";
DROP TABLE "OAUTH2";
DROP TABLE "OAUTH1";
DROP TABLE "USER";
